CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -O2
LDFLAGS =

# Targets
VM = vm
TEST = test_vm

# Source files
VM_SRC = vm.c
TEST_SRC = test_vm.c

# Python bytecode compiler and test files
PYTHON = python3
BYTECODE_COMPILER = robots-bytecode.py
TEST_ROOMS = TEST_ROOM_1.txt TEST_ROOM_2.txt TEST_ROOM_3.txt TEST_ROOM_4.txt
BYTECODE_FILES = test_room_1.oof test_room_2.oof test_room_3.oof test_room_4.oof

.PHONY: all clean test test-c test-bytecode

all: $(VM)

$(VM): $(VM_SRC)
	$(CC) $(CFLAGS) -o $(VM) $(VM_SRC) $(LDFLAGS)

$(TEST): $(TEST_SRC) $(VM_SRC)
	$(CC) $(CFLAGS) -DTEST_BUILD -c $(VM_SRC) -o vm.o
	$(CC) $(CFLAGS) -DTEST_BUILD -o $(TEST) $(TEST_SRC) vm.o $(LDFLAGS)

test-c: $(TEST)
	@echo "=== Running C unit tests ==="
	./$(TEST)

test-bytecode: $(VM)
	@echo ""
	@echo "=== Compiling test rooms to bytecode ==="
	$(PYTHON) $(BYTECODE_COMPILER)
	@echo ""
	@echo "=== Running C VM on generated bytecode files ==="
	@for file in $(BYTECODE_FILES); do \
		echo ""; \
		echo "Running $$file..."; \
		./$(VM) $$file || exit 1; \
	done
	@echo ""
	@echo "=== All bytecode tests passed ==="

test: test-c test-bytecode

clean:
	rm -f $(VM) $(TEST) vm.o $(BYTECODE_FILES)
